apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName }}-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.database.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.database.storage.size }}
