apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.appName }}-aws-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "guess-the-number/database"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: db-username
          - path: password
            objectAlias: db-password
          - path: database
            objectAlias: db-name
          - path: host
            objectAlias: db-host
          - path: port
            objectAlias: db-port
  # Create a Kubernetes Secret from the fetched data
  secretObjects:
  - secretName: {{ .Values.appName }}-db-secret
    type: Opaque
    data:
    - objectName: db-username
      key: username
    - objectName: db-password
      key: password
    - objectName: db-name
      key: database
    - objectName: db-host
      key: host
    - objectName: db-port
      key: port
